name: iOS Development Build

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - profile

jobs:
  build-ios-dev:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Get version info
      id: version
      run: |
        echo "version=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
        echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    
    - name: Build iOS Development
      run: flutter build ios --${{ github.event.inputs.build_type }} --no-codesign
    
    - name: Create Development IPA
      run: |
        cd ios
        mkdir -p build/ios-dev
        cd build/ios-dev
        mkdir -p Payload/Runner.app
        # Copy the built app
        cp -r ../../build/ios/iphoneos/Runner.app Payload/
        # Create IPA with clear naming
        zip -r "HealthyPathway-iPhone12Pro-DEV-${{ github.event.inputs.build_type }}-${{ steps.version.outputs.version }}-${{ steps.version.outputs.commit }}.ipa" Payload/
    
    - name: Upload Development IPA
      uses: actions/upload-artifact@v3
      with:
        name: "HealthyPathway-iPhone12Pro-DEV-${{ github.event.inputs.build_type }}-${{ steps.version.outputs.version }}-${{ steps.version.outputs.commit }}"
        path: ios/build/ios-dev/HealthyPathway-iPhone12Pro-DEV-${{ github.event.inputs.build_type }}-${{ steps.version.outputs.version }}-${{ steps.version.outputs.commit }}.ipa
        retention-days: 3
    
    - name: Cleanup old dev artifacts
      uses: actions/github-script@v6
      with:
        script: |
          const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId,
          });
          
          // Keep only the latest 1 dev artifact
          const devArtifacts = artifacts.data.artifacts.filter(artifact => 
            artifact.name.startsWith('HealthyPathway-iPhone12Pro-DEV-')
          );
          
          if (devArtifacts.length > 1) {
            const artifactsToDelete = devArtifacts.slice(1);
            for (const artifact of artifactsToDelete) {
              await github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id,
              });
            }
          } 