name: iOS Minimal Build

on:
  workflow_dispatch: # Manual trigger only

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Install pods
      run: |
        cd ios
        pod install
        cd ..
      
    - name: Build
      run: flutter build ios --release --no-codesign 