name: iOS Build

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/workflows/ios-build.yml'
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Get version info
      id: version
      run: |
        echo "version=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
        echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    
    - name: Build iOS (Development)
      run: flutter build ios --debug --no-codesign
    
    - name: Create IPA manually
      run: |
        cd ios
        mkdir -p build/ios
        # Create a simple IPA structure for development
        cd build/ios
        mkdir -p Payload/Runner.app
        # Copy the built app
        cp -r ../../build/ios/iphoneos/Runner.app Payload/
        # Create IPA with clear naming
        zip -r "HealthyPathway-iPhone12Pro-${{ steps.version.outputs.version }}-${{ steps.version.outputs.commit }}.ipa" Payload/
    
    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: "HealthyPathway-iPhone12Pro-${{ steps.version.outputs.version }}-${{ steps.version.outputs.commit }}"
        path: ios/build/ios/HealthyPathway-iPhone12Pro-${{ steps.version.outputs.version }}-${{ steps.version.outputs.commit }}.ipa
        retention-days: 7
    
    - name: Cleanup old artifacts
      uses: actions/github-script@v6
      with:
        script: |
          const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId,
          });
          
          // Keep only the latest 1 artifact
          const iosArtifacts = artifacts.data.artifacts.filter(artifact => 
            artifact.name.startsWith('HealthyPathway-iPhone12Pro-')
          );
          
          if (iosArtifacts.length > 1) {
            const artifactsToDelete = iosArtifacts.slice(1);
            for (const artifact of artifactsToDelete) {
              await github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id,
              });
            }
          } 