name: Build iOS IPA (Debug)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allows manual trigger

jobs:
  build-ios-debug:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.3'
        channel: 'stable'
        
    - name: Show Flutter version
      run: flutter --version
      
    - name: Show project structure
      run: |
        echo "=== Project Structure ==="
        ls -la
        echo "=== iOS Directory ==="
        ls -la ios/
        echo "=== Flutter Directory ==="
        ls -la ios/Flutter/
        
    - name: Get Flutter dependencies
      run: flutter pub get
      
    - name: Check Flutter doctor
      run: flutter doctor -v
      
    - name: Generate iOS files
      run: flutter build ios --no-codesign --debug
      
    - name: Show generated files
      run: |
        echo "=== Generated Files ==="
        ls -la ios/Flutter/
        echo "=== Podfile exists ==="
        ls -la ios/Podfile || echo "Podfile not found"
        
    - name: Install iOS dependencies
      run: |
        cd ios
        pod install --verbose
        cd ..
        
    - name: Show pod installation results
      run: |
        echo "=== Pod Installation Results ==="
        ls -la ios/Pods/
        
    - name: Check Xcode project
      run: |
        echo "=== Xcode Project Check ==="
        ls -la ios/Runner.xcodeproj/
        ls -la ios/Runner.xcworkspace/
        
    - name: Build iOS IPA (Debug)
      run: |
        echo "=== Starting IPA Build ==="
        flutter build ipa --debug --no-codesign --verbose
        echo "=== IPA Build Completed ==="
      
    - name: Show build results
      run: |
        echo "=== Build Results ==="
        echo "Checking for IPA files..."
        find build/ -name "*.ipa" -type f
        echo "Checking build directory structure..."
        ls -la build/ || echo "Build directory not found"
        ls -la build/ios/ || echo "iOS build directory not found"
        ls -la build/ios/ipa/ || echo "IPA directory not found"
        echo "Checking for any build artifacts..."
        find build/ -type f -name "*.app" || echo "No .app files found"
        
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: ios-debug-build
        path: build/ios/ipa/*.ipa
        retention-days: 30
        
    - name: Upload build logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-logs-debug
        path: |
          build/
          ios/Pods/
        retention-days: 7
        
    - name: Upload Xcode logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: xcode-logs
        path: |
          ~/Library/Developer/Xcode/DerivedData/
        retention-days: 7 