name: iOS Guaranteed Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allows manual trigger

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: 'stable'
        
    - name: Show Flutter version
      run: flutter --version
      
    - name: Clean project
      run: |
        flutter clean
        flutter pub get
        
    - name: Check Flutter doctor
      run: flutter doctor -v
      
    - name: Install iOS dependencies
      run: |
        cd ios
        pod deintegrate || true
        pod cache clean --all || true
        pod install --repo-update
        cd ..
        
    - name: Verify iOS setup
      run: |
        echo "Checking iOS configuration..."
        ls -la ios/
        ls -la ios/Runner.xcodeproj/ || echo "Xcode project not found"
        
    - name: Build iOS IPA
      run: |
        echo "Building iOS IPA..."
        flutter build ipa --release --no-codesign --verbose
        
    - name: Check build results
      run: |
        echo "Checking build results..."
        ls -la build/ || echo "Build directory not found"
        ls -la build/ios/ || echo "iOS build directory not found"
        find build/ -name "*.ipa" -type f || echo "No IPA files found"
        
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: healthy-pathway-ipa
        path: build/ios/ipa/*.ipa
        retention-days: 30
        if-no-files-found: warn
        
    - name: Upload build logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-logs
        path: build/
        retention-days: 7 