name: iOS Simple & Reliable

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allows manual trigger

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.3'
        channel: 'stable'
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Install iOS dependencies
      run: |
        cd ios
        pod install
        cd ..
        
    - name: Build iOS IPA
      run: flutter build ipa --release --no-codesign
      
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: healthy-pathway-ipa
        path: build/ios/ipa/*.ipa
        retention-days: 30 