name: Build iOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build iOS app (release for device)
        run: flutter build ipa --release

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-ipa
          path: build/ios/ipa/*.ipa 